# -*- coding: utf-8 -*-
"""Semana_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11bA_QLD2x8yR-5KE2yODUcnqnpanSLFm

# <img src="https://github.com/sthemonica/alura-voz/blob/main/logos-alura%20voz/Logo%20Alura%20Voz-03.png?raw=true" alt="Alura-voz" width=40/>  Semana 01: Análise e Limpeza de Dados


O objetivo da semana 01 é consumir a base de dados no formato [JSON](https://www.alura.com.br/artigos/o-que-e-json?gclid=CjwKCAjwv-GUBhAzEiwASUMm4paDYb7hUlWkXsH9sjRjng6Po7CnZzQwGyvGXmqMarXdJamYs10VUhoC4Z4QAvD_BwE) fornecido pela empresa fictícia Alura Voz e:
 - Entender quais informações o conjunto de dados possui;
 - Analisar quais os  tipos de dados existem;
 - Verificar quais são as inconsistências nos dados;
 - Corrigir inconsistências nos dados;
 - Traduzir as colunas;
 - Criar colunas de contas diárias;

## Entendendo os tipos de dados
"""

# Importando bibliotecas

import pandas as pd
import numpy as np

# Lendo dados do banco (Alura Voz)
base_dados_alura_voz = pd.read_json('https://raw.githubusercontent.com/LeoGrochoski/Alura-Data-Challenge-2022/main/Alura%20Data%20Challenge/Dados/Alura-voz-banco-dados.json')

# Exibindo base de dados importada
base_dados_alura_voz.head()

# Identificando as variaveis da base de dados

base_dados_alura_voz.keys()

base_dados_alura_voz['customerID'][0]

base_dados_alura_voz['Churn'][0]

base_dados_alura_voz['customer'][0]

base_dados_alura_voz['phone'][0]

base_dados_alura_voz['internet'][0]

base_dados_alura_voz['account'][0]